on:
  push:
    branches:
    - main
jobs:
  release:
    name: Build pdfgrep wasm and js files
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build docker images
      run: docker build -t pdfgrep-wasm .
    - uses: shrink/actions-docker-extract@v1
      id: extract
      with:
        image: pdfgrep-wasm
        path: /src/target/.
    - name: Upload Dist
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.extract.outputs.destination }}
        name: dist
